### ISSUE TITLE
Not working if source files under a sub-directory

### ISSUE THREAD

**Issue by nicolashery** [bbugh/SublimeLinter-contrib-elm-make#2]
My project has all the `.elm` files under `src/`, and I specified `"source-directories": ["src"]` in `elm-package.json`.

Running:

``` bash
$ cd project/
$ elm-make --warn --report=json src/App.elm
Successfully generated elm.js
```

Works as expected. But running the command from `src/` (what is run by SublimeLinter I'm guessing):

``` bash
$ cd project/src/
$ elm-make --warn --report=json App.elm
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0

Do you approve of this plan? (y/n)
```

Doesn't work. Can we tell SublimeLinter to run the command from the project's root directory? Doing a quick search, I couldn't find anything...

**Comment by chalmagean** [comment]
+1

**Comment by dancras** [comment]
+1 pretty useless without this fix as it's impossible to structure code, or use anyone else's repo.

In the meantime I've cloned tgecho's fork into my sublime text Packages dir as a manual install.

**Comment by bbugh** [comment]
Sorry about that, I switched to Atom and haven't touched this in a while. @dancras and @chalmagean if y'all can confirm @tgecho's pull request works for you, I'll accept it.

**Comment by dancras** [comment]
Works for me 👍
