### ISSUE TITLE
How do I setup rules?

### ISSUE THREAD

**Issue by sircharleswatson** [bbugh/SublimeLinter-contrib-elm-make#3]
I'm not sure how this actually works or how I can see linting errors in sublime. Where can I setup rules for things like tabs vs spaces, indentation, etc? And what rules are available?

**Comment by tgecho** [comment]
This plugin seems to be more focused on running elm-make and showing its compile errors through the linter system. More traditional "syntax" style linting would be a slightly different concern. For what it's worth [Elm Language Support](https://packagecontrol.io/packages/Elm%20Language%20Support) can automatically run elm-format, which basically "lints" stylistic rules such as indentation by force. :)

**Comment by bbugh** [comment]
@sircharleswatson this is simply for catching errors easily, it doesn't do any fancy formatting or anything. I recommend using the package @tgecho mentioned if you're looking for more than that.
